import DEFAULTS from '../common';
interface COLORS {
  PRIMARY: string;
  SECONDARY: string;
  TERTIARY: string;
  QUATERNARY: string;
  QUINARY: string;
}

const COLORS: COLORS = {
  PRIMARY: '#F2CF63',
  SECONDARY: '#F2A30F',
  TERTIARY: '#F2B90F',
  QUATERNARY: '#8C600D',
  QUINARY: '#261901',
};

export default {
  ...DEFAULTS.COLORS,
  ...COLORS,
  BACKGROUND: {
    PRIMARY: COLORS.PRIMARY,
    SECONDARY: COLORS.SECONDARY,
  },
  TEXT: {
    PRIMARY: COLORS.QUINARY,
    SECONDARY: COLORS.QUATERNARY,
  },
};
